"""Add organization and defaults

Revision ID: 1713379573
Revises: 
Create Date: 2024-04-17 18:46:13.148882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1713379573'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('default',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('organization', sa.String(), nullable=False))
    op.alter_column('account', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('account', 'account_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'account_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('account', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('account', 'organization')
    # ### end Alembic commands ###
