"""Add new metric history table

Revision ID: 1714683528
Revises: 1714531137
Create Date: 2024-05-02 20:58:49.167214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1714683528'
down_revision: Union[str, None] = '1714531137'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Integer(), nullable=False),
    sa.Column('metric_day', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'account', ['account_id'])
    op.create_unique_constraint(None, 'application', ['application_id'])
    op.create_unique_constraint(None, 'candidate', ['candidate_id'])
    op.create_unique_constraint(None, 'interview', ['interview_id'])
    op.create_unique_constraint(None, 'role', ['role_id'])
    op.create_unique_constraint(None, 'skill', ['skill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'interview', type_='unique')
    op.drop_constraint(None, 'candidate', type_='unique')
    op.drop_constraint(None, 'application', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_table('metric_history')
    # ### end Alembic commands ###
