"""Revert previous change

Revision ID: 1714525026
Revises: 1714524810
Create Date: 2024-05-01 00:57:06.428591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1714525026'
down_revision: Union[str, None] = '1714524810'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('application_creator_id_fkey', 'application', type_='foreignkey')
    op.drop_column('application', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('application_creator_id_fkey', 'application', 'account', ['creator_id'], ['account_id'])
    # ### end Alembic commands ###
