"""Update backrefs

Revision ID: 1714525870
Revises: 1714525391
Create Date: 2024-05-01 01:11:11.068752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1714525870'
down_revision: Union[str, None] = '1714525391'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_candidate_speaking',
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('speaking_time', sa.Integer(), nullable=True),
    sa.Column('wpm', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.candidate_id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.interview_id'], )
    )
    op.create_table('interview_interviewer_speaking',
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('interviewer_id', sa.Integer(), nullable=True),
    sa.Column('speaking_time', sa.Integer(), nullable=True),
    sa.Column('wpm', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.interview_id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['account.account_id'], )
    )
    op.drop_table('interview_speaking')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_speaking',
    sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interviewer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('speaking_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wpm', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.candidate_id'], name='interview_speaking_candidate_id_fkey'),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.interview_id'], name='interview_speaking_interview_id_fkey'),
    sa.ForeignKeyConstraint(['interviewer_id'], ['account.account_id'], name='interview_speaking_interviewer_id_fkey')
    )
    op.drop_table('interview_interviewer_speaking')
    op.drop_table('interview_candidate_speaking')
    # ### end Alembic commands ###
