"""More bug fixes

Revision ID: 1714528019
Revises: 1714526581
Create Date: 2024-05-01 01:46:59.490791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1714528019'
down_revision: Union[str, None] = '1714526581'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_skill_score', sa.Column('skill_id', sa.Integer(), nullable=True))
    op.drop_constraint('interview_skill_score_skill_name_fkey', 'interview_skill_score', type_='foreignkey')
    op.create_foreign_key(None, 'interview_skill_score', 'skill', ['skill_id'], ['skill_id'])
    op.drop_column('interview_skill_score', 'skill_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_skill_score', sa.Column('skill_name', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interview_skill_score', type_='foreignkey')
    op.create_foreign_key('interview_skill_score_skill_name_fkey', 'interview_skill_score', 'skill', ['skill_name'], ['skill_id'])
    op.drop_column('interview_skill_score', 'skill_id')
    # ### end Alembic commands ###
