"""

Revision ID: 1714528946
Revises: 1714528019
Create Date: 2024-05-01 02:02:26.406838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1714528946'
down_revision: Union[str, None] = '1714528019'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_candidate_speaking')
    op.add_column('interview', sa.Column('speaking_time', sa.Integer(), nullable=True))
    op.add_column('interview', sa.Column('wpm', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview', 'wpm')
    op.drop_column('interview', 'speaking_time')
    op.create_table('interview_candidate_speaking',
    sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('speaking_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wpm', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.candidate_id'], name='interview_candidate_speaking_candidate_id_fkey'),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.interview_id'], name='interview_candidate_speaking_interview_id_fkey')
    )
    # ### end Alembic commands ###
