"""Add candidate_id to Interview

Revision ID: 1714526405
Revises: 1714525870
Create Date: 2024-05-01 01:20:06.186441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1714526405'
down_revision: Union[str, None] = '1714525870'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('candidate_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'interview', 'candidate', ['candidate_id'], ['candidate_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.drop_column('interview', 'candidate_id')
    # ### end Alembic commands ###
