"""Add creator to Application

Revision ID: 1714524810
Revises: 1714523771
Create Date: 2024-05-01 00:53:30.807077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1714524810'
down_revision: Union[str, None] = '1714523771'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('application_candidate_id_fkey', 'application', type_='foreignkey')
    op.create_foreign_key(None, 'application', 'account', ['creator_id'], ['account_id'])
    op.create_foreign_key(None, 'application', 'candidate', ['candidate_id'], ['candidate_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.create_foreign_key('application_candidate_id_fkey', 'application', 'account', ['candidate_id'], ['account_id'])
    op.drop_column('application', 'creator_id')
    # ### end Alembic commands ###
