"""Update backrefs

Revision ID: 1714523771
Revises: 1714516915
Create Date: 2024-05-01 00:36:11.538162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1714523771'
down_revision: Union[str, None] = '1714516915'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('candidate_id', sa.Integer(), nullable=False))
    op.drop_constraint('unique_role_candidate', 'application', type_='unique')
    op.create_unique_constraint('unique_role_candidate', 'application', ['role_id', 'candidate_id'])
    op.create_unique_constraint(None, 'application', ['application_id'])
    op.drop_constraint('application_candidate_email_fkey', 'application', type_='foreignkey')
    op.create_foreign_key(None, 'application', 'account', ['candidate_id'], ['account_id'])
    op.drop_column('application', 'candidate_email')
    op.create_unique_constraint(None, 'candidate', ['candidate_id'])
    op.create_unique_constraint(None, 'interview', ['interview_id'])
    op.create_unique_constraint(None, 'role', ['role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'interview', type_='unique')
    op.drop_constraint(None, 'candidate', type_='unique')
    op.add_column('application', sa.Column('candidate_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.create_foreign_key('application_candidate_email_fkey', 'application', 'account', ['candidate_email'], ['email'])
    op.drop_constraint(None, 'application', type_='unique')
    op.drop_constraint('unique_role_candidate', 'application', type_='unique')
    op.create_unique_constraint('unique_role_candidate', 'application', ['role_id', 'candidate_email'])
    op.drop_column('application', 'candidate_id')
    # ### end Alembic commands ###
