"""Database changes for API implementation

Revision ID: 1715626668
Revises: 1715028595
Create Date: 2024-05-13 18:57:49.166677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1715626668'
down_revision: Union[str, None] = '1715028595'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_interviewer')
    op.create_unique_constraint(None, 'account', ['account_id'])
    op.create_unique_constraint(None, 'application', ['application_id'])
    op.create_unique_constraint(None, 'candidate', ['candidate_id'])
    op.add_column('interview', sa.Column('audio_url_preprocessed', sa.String(), nullable=True))
    op.add_column('interview', sa.Column('video_url_preprocessed', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'interview', ['interview_id'])
    op.add_column('interview_interviewer_speaking', sa.Column('interviewer_notes', sa.String(), nullable=True))
    op.add_column('interview_interviewer_speaking', sa.Column('interviewer_score', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'role', ['role_id'])
    op.create_unique_constraint(None, 'skill', ['skill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_column('interview_interviewer_speaking', 'interviewer_score')
    op.drop_column('interview_interviewer_speaking', 'interviewer_notes')
    op.drop_constraint(None, 'interview', type_='unique')
    op.drop_column('interview', 'video_url_preprocessed')
    op.drop_column('interview', 'audio_url_preprocessed')
    op.drop_constraint(None, 'candidate', type_='unique')
    op.drop_constraint(None, 'application', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    op.create_table('interview_interviewer',
    sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interviewer_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('candidate_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.interview_id'], name='interview_interviewer_interview_id_fkey'),
    sa.ForeignKeyConstraint(['interviewer_email'], ['account.email'], name='interview_interviewer_interviewer_email_fkey')
    )
    # ### end Alembic commands ###
