"""Have autoincrement start at max column value

Revision ID: 1715028594
Revises: 1715028226
Create Date: 2024-05-06 20:49:54.653825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1715028594'
down_revision: Union[str, None] = '1715028226'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Set the current value of the sequences to the maximum value of the respective columns
    op.execute("SELECT setval('account_account_id_seq', (SELECT MAX(account_id) FROM account))")
    op.execute("SELECT setval('metric_history_id_seq', (SELECT MAX(id) FROM metric_history))")
    op.execute("SELECT setval('skill_skill_id_seq', (SELECT MAX(skill_id) FROM skill))")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
