"""Add recall_id column to Interview

Revision ID: 1718138249
Revises: 1715626668
Create Date: 2024-06-11 20:37:29.965441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1718138249'
down_revision: Union[str, None] = '1715626668'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['account_id'])
    op.create_unique_constraint(None, 'application', ['application_id'])
    op.create_unique_constraint(None, 'candidate', ['candidate_id'])
    op.add_column('interview', sa.Column('recall_id', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'interview', ['interview_id'])
    op.create_unique_constraint(None, 'role', ['role_id'])
    op.create_unique_constraint(None, 'skill', ['skill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'interview', type_='unique')
    op.drop_column('interview', 'recall_id')
    op.drop_constraint(None, 'candidate', type_='unique')
    op.drop_constraint(None, 'application', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
