"""Add transcription storage

Revision ID: 1719870736
Revises: 1719272098
Create Date: 2024-07-01 21:52:16.908029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1719870736'
down_revision: Union[str, None] = '1719272098'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('engagement', sa.String(), nullable=True),
    sa.Column('speaker', sa.String(), nullable=True),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    sa.ForeignKeyConstraint(['interview_id'], ['interview.interview_id']) 
    op.create_unique_constraint(None, 'account', ['account_id'])
    op.create_unique_constraint(None, 'application', ['application_id'])
    op.create_unique_constraint(None, 'candidate', ['candidate_id'])
    op.create_unique_constraint(None, 'interview', ['interview_id'])
    op.create_unique_constraint(None, 'role', ['role_id'])
    op.create_unique_constraint(None, 'skill', ['skill_id'])

    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transcript_lines_interview_id_fkey', 'transcript_lines', type_='foreignkey')
    op.drop_constraint(None, 'skill', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'interview', type_='unique')
    op.drop_constraint(None, 'candidate', type_='unique')
    op.drop_constraint(None, 'application', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_table('transcript_lines')
    # ### end Alembic commands ###
