"""Fix transcript database error

Revision ID: 1719883885
Revises: 1719882333
Create Date: 2024-07-02 01:31:26.111844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1719883885'
down_revision: Union[str, None] = '1719882333'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript_lines', sa.Column('interview_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transcript_lines', 'interview', ['interview_id'], ['interview_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcript_lines', type_='foreignkey')
    op.drop_column('transcript_lines', 'interview_id')
    # ### end Alembic commands ###
