"""Add new Onboarding column to Account

Revision ID: 1724528431
Revises: 
Create Date: 2024-08-24 12:40:32.641527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1724528431'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('default',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add the column without NOT NULL constraint
    op.add_column('account', sa.Column('onboarded', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))

    # Populate the column
    op.execute('UPDATE account SET onboarded = FALSE WHERE onboarded IS NULL')

    # Alter the column to enforce the NOT NULL constraint
    op.alter_column('account', 'onboarded', nullable=False)
    op.create_unique_constraint(None, 'account', ['account_id'])
    op.create_unique_constraint(None, 'application', ['application_id'])
    op.create_unique_constraint(None, 'candidate', ['candidate_id'])
    op.create_unique_constraint(None, 'interview', ['interview_id'])
    op.create_unique_constraint(None, 'role', ['role_id'])
    op.create_unique_constraint(None, 'skill', ['skill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'interview', type_='unique')
    op.drop_constraint(None, 'candidate', type_='unique')
    op.drop_constraint(None, 'application', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_column('account', 'onboarded')
    # ### end Alembic commands ###
