"""Add Onboarding fields to database

Revision ID: 1725570562
Revises: 1724528431
Create Date: 2024-09-05 14:09:23.642687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1725570562'
down_revision: Union[str, None] = '1724528431'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('organization_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hiring_document_url', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('organization_id'),
    sa.UniqueConstraint('organization_id')
    )
    op.alter_column('account', 'onboarded',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('account', 'organization')
    op.add_column('role', sa.Column('position_type', sa.String(), nullable=True))
    op.add_column('role', sa.Column('department', sa.String(), nullable=True))
    op.add_column('role', sa.Column('responsibilities', sa.String(), nullable=True))
    op.add_column('role', sa.Column('requirements', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'requirements')
    op.drop_column('role', 'responsibilities')
    op.drop_column('role', 'department')
    op.drop_column('role', 'position_type')
    op.add_column('account', sa.Column('organization', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('account', 'onboarded',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_table('organization')
    # ### end Alembic commands ###
