"""Make organization nullable

Revision ID: 1725571705
Revises: 1725571287
Create Date: 2024-09-05 14:28:25.762940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1725571705'
down_revision: Union[str, None] = '1725571287'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account', 'organization', ['organization_id'], ['organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'organization_id')
    # ### end Alembic commands ###
