"""Remove skill tables for each type

Revision ID: 1725576066
Revises: 1725571894
Create Date: 2024-09-05 15:41:06.908103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1725576066'
down_revision: Union[str, None] = '1725571894'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_hard_skill')
    op.drop_table('role_soft_skill')
    op.drop_table('role_behavioral_skill')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_behavioral_skill',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], name='role_behavioral_skill_role_id_fkey'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skill_id'], name='role_behavioral_skill_skill_id_fkey'),
    sa.PrimaryKeyConstraint('role_id', 'skill_id', name='role_behavioral_skill_pkey')
    )
    op.create_table('role_soft_skill',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], name='role_soft_skill_role_id_fkey'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skill_id'], name='role_soft_skill_skill_id_fkey'),
    sa.PrimaryKeyConstraint('role_id', 'skill_id', name='role_soft_skill_pkey')
    )
    op.create_table('role_hard_skill',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], name='role_hard_skill_role_id_fkey'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skill_id'], name='role_hard_skill_skill_id_fkey'),
    sa.PrimaryKeyConstraint('role_id', 'skill_id', name='role_hard_skill_pkey')
    )
    # ### end Alembic commands ###
