"""Add Google Calendar token field

Revision ID: 1726143130
Revises: 1725576066
Create Date: 2024-09-12 05:12:11.306799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1726143130'
down_revision: Union[str, None] = '1725576066'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('google_calendar_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'google_calendar_token')
    # ### end Alembic commands ###
