"""

Revision ID: 1728761698
Revises: 1726143130
Create Date: 2024-10-12 12:34:58.913244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1728761698'
down_revision: Union[str, None] = '1726143130'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['account_id'])
    op.create_unique_constraint(None, 'application', ['application_id'])
    op.create_unique_constraint(None, 'candidate', ['candidate_id'])
    op.create_unique_constraint(None, 'interview', ['interview_id'])
    op.create_unique_constraint(None, 'organization', ['organization_id'])
    op.create_unique_constraint(None, 'role', ['role_id'])
    op.create_unique_constraint(None, 'skill', ['skill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'organization', type_='unique')
    op.drop_constraint(None, 'interview', type_='unique')
    op.drop_constraint(None, 'candidate', type_='unique')
    op.drop_constraint(None, 'application', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
